# This makefile is needed to compile in kred, not used in standalone compilation
ERLC_FLAGS+= -I ../../../test/test/include -pz ../../../test/shared/ebin
include ../vsn.mk
include ../../../support/stderl.mk